import { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { TrendingUp, LayoutList } from 'lucide-react';
import api from '@/lib/api';
import { toast } from 'sonner';

interface BvHistory {
    month: number;
    monthName: string;
    year: number;
    totalBV: number;
}

export default function CompanyBvHistory() {
    const [history, setHistory] = useState<BvHistory[]>([]);
    const [loading, setLoading] = useState(true);
    const [currentMonthBV, setCurrentMonthBV] = useState(0);

    useEffect(() => {
        fetchBvHistory();
    }, []);

    const fetchBvHistory = async () => {
        try {
            setLoading(true);
            const res = await api.get('/api/v1/admin/company-bv');
            if (res.data?.success) {
                setHistory(res.data.data.history);
                setCurrentMonthBV(res.data.data.currentMonthBV);
            }
        } catch (error: any) {
            toast.error(error.response?.data?.message || 'Failed to fetch company BV history');
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="space-y-6">
            <div className="flex flex-col gap-2">
                <h1 className="text-3xl font-bold tracking-tight">Company BV Tracking</h1>
                <p className="text-muted-foreground">Month-wise breakdown of total Business Volume generated by Franchise Sales.</p>
            </div>

            <div className="grid gap-4 md:grid-cols-3">
                <Card className="border-border">
                    <CardHeader className="flex flex-row items-center justify-between pb-2">
                        <CardTitle className="text-sm font-medium text-muted-foreground">Current Month BV</CardTitle>
                        <TrendingUp className="h-5 w-5 text-emerald-500" />
                    </CardHeader>
                    <CardContent>
                        <div className="text-3xl font-bold text-foreground">{currentMonthBV.toLocaleString('en-IN')}</div>
                        <p className="text-xs text-muted-foreground mt-1">Total active franchise BV this month</p>
                    </CardContent>
                </Card>
            </div>

            <Card className="glass border-border/50">
                <CardHeader>
                    <CardTitle className="flex items-center gap-2">
                        <LayoutList className="w-5 h-5 text-primary" />
                        Monthly BV History
                    </CardTitle>
                    <CardDescription>Comprehensive record of past business volume generation.</CardDescription>
                </CardHeader>
                <CardContent>
                    <div className="rounded-md border border-border/50">
                        <Table>
                            <TableHeader>
                                <TableRow className="bg-muted/50">
                                    <TableHead>Month</TableHead>
                                    <TableHead>Year</TableHead>
                                    <TableHead className="text-right">Total BV Generated</TableHead>
                                </TableRow>
                            </TableHeader>
                            <TableBody>
                                {loading ? (
                                    <TableRow>
                                        <TableCell colSpan={3} className="text-center py-8">
                                            <div className="flex items-center justify-center gap-2">
                                                <div className="w-4 h-4 rounded-full border-2 border-primary border-t-transparent animate-spin" />
                                                Loading history...
                                            </div>
                                        </TableCell>
                                    </TableRow>
                                ) : history.length === 0 ? (
                                    <TableRow>
                                        <TableCell colSpan={3} className="text-center py-8 text-muted-foreground">
                                            No historical BV data found.
                                        </TableCell>
                                    </TableRow>
                                ) : (
                                    history.map((record) => (
                                        <TableRow key={`${record.month}-${record.year}`}>
                                            <TableCell className="font-medium text-foreground">{record.monthName}</TableCell>
                                            <TableCell className="text-muted-foreground">{record.year}</TableCell>
                                            <TableCell className="text-right font-bold text-emerald-600 dark:text-emerald-400 text-lg">
                                                {record.totalBV.toLocaleString('en-IN')}
                                            </TableCell>
                                        </TableRow>
                                    ))
                                )}
                            </TableBody>
                        </Table>
                    </div>
                </CardContent>
            </Card>
        </div>
    );
}
